/* Generated by tools/build-pages.mjs. Edit index.html instead. */
window.PORTFOLIO_SECTIONS = [
    {
        id: "profile-section",
        page: "about.html",
        title: "🪄 About Me",
        category: null,
        description: "",
    },
    {
        id: "project-keeptive",
        page: "keeptive.html",
        title: "🟢 Keeptive",
        category: "Full-Stack",
        description: "Auto Clicker & Discreet Window Interaction Tool",
    },
    {
        id: "project-genetic-algorithm",
        page: "genetic-algorithm.html",
        title: "🧬 Genetic Algorithm",
        category: "Full-Stack",
        description: "GA for Nutritional Diet Optimization",
    },
    {
        id: "project-restful-api",
        page: "restful-api.html",
        title: "🔗 RESTful API",
        category: "Full-Stack",
        description: "RESTful User Management API",
    },
    {
        id: "project-dfa",
        page: "dfa.html",
        title: "🔀 Deterministic Finite Automaton",
        category: "Full-Stack",
        description: "HTTPS URL Extractor Using DFA",
    },
    {
        id: "project-analyzer",
        page: "analyzer.html",
        title: "📚 Lexical, Syntactic & Semantic Analyzer",
        category: "Full-Stack",
        description:
            "SQL Statement Analyzer With Lexer, Parser And Semantic Checker",
    },
    {
        id: "project-disney-redesign",
        page: "disney-redesign.html",
        title: "🏰 Disney+ Redesign",
        category: "UI/UX Design",
        description: "Modern Streaming Platform Interface",
    },
    {
        id: "project-qualitor",
        page: "qualitor.html",
        title: "🎯 QualiTor",
        category: "UI/UX Design",
        description:
            "MoProSoft-Based System for Creating Software Quality Manuals",
    },
    {
        id: "contact-section",
        page: "contact.html",
        title: "✉️ Contact",
        category: null,
        description: "",
    },
];
